/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111719-gb98ee1a355-20230808"
#endif /* AVUTIL_FFVERSION_H */
